[build]
command = "yarn install && yarn build"
publish = "build"

[build.environment]
NODE_VERSION = "16"
YARN_VERSION = "1.22.19"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
YARN_ENABLE_SCRIPTS = "true"
NODE_OPTIONS = "--openssl-legacy-provider" 