[build]
command = "npm install && npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "16"
NPM_CONFIG_LEGACY_PEER_DEPS = "true"
NPM_CONFIG_ENGINE_STRICT = "true"
NPM_CONFIG_PACKAGE_LOCK = "true" 